version: "3.1"

services:
  front:
    image: ponche/studi-front
    restart: always
    ports:
      - 8080:8080

  api:
    image: ponche/studi-api
    restart: always
    environment:
      DB_USER: root
      HOST: 0.0.0.0
      PORT: 1337
      URL_FRONT: https://studi.remi-ponche.fr
      APP_KEYS: "toBeModified1, toBeModified2"
      API_TOKEN_SALT: tobemodified
      ADMIN_JWT_SECRET: tobemodified
      TRANSFER_TOKEN_SALT: tobemodified
      JWT_SECRET: tobemodified
      TOKEN_STRIPE: tobemodified
      ENDPOINT_SECRET_STRIPE: tobemodified
      DB_PASSWORD: changeMe
    ports:
      - 3000:1337

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: changeMe
