version: "3.1"

services:
  front:
    build: front
    restart: always
    environment:
      URL_API: http://localhost:3000
    ports:
      - 80:8080

  api:
    build: api
    restart: always
    environment:
      DB_USER: root
      DB_PASSWORD: changeMe
    ports:
      - 3000:3000

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: changeMe
